### ISSUE TITLE
英文与中文结合的名词，中英文之间是否需要空格？

### ISSUE THREAD

**Issue by Taskeren** [mzlogin/chinese-copywriting-guidelines#14]
英文与中文结合的名词，中英文之间是否需要空格？
比如： “Shadowsocks服务器”还是“Shadowsocks 服务器”？

**Comment by leviding** [comment]
个人认为需要加空格

**Comment by brlin-tw** [comment]
个人目前是完全不加手动留白派
等软件支援之后才不用改回来

**Comment by owennn7777** [comment]
看你想把这些内容展示在哪里？官网等正式场景最好留白「Shadowsocks 服务器」，但如果是自己日常记录就不需要了。一些数据展示也是如此。

林博仁(Buo-ren Lin) <notifications@github.com> 于2018年12月18日周二 下午11:06写道：

**Comment by uiosun** [comment]
@owennn7777 
私以为「Shadowsocks 服务器」本就是两个词，单说 SS 也可以起到一样的效果。

譬如「UP主」这样的词汇，才能体现这道问题的困惑。

附带例句：

> 原句：UP主讲了一句话
> 留白：UP 主讲了一句话

看起来真的很怪异

**Comment by brlin-tw** [comment]
> @owennn7777
> 私以为「Shadowsocks 服务器」本就是两个词，单说 SS 也可以起到一样的效果。
> 
> 譬如「UP主」这样的词汇，才能体现这道问题的困惑。
> 
> 附带例句：
> 
> > 原句：UP主讲了一句话
> > 留白：UP 主讲了一句话
> 
> 看起来真的很怪异

個人在第二個情境會選擇不留白
