### ISSUE TITLE
提问：什么是 UGC？

### ISSUE THREAD

**Issue by brlin-tw** [mzlogin/chinese-copywriting-guidelines#16]
![default](https://user-images.githubusercontent.com/13408130/50163044-924c0780-031a-11e9-9732-cd227b59e3cc.png)

如题。

**Comment by Teakowa** [comment]
[用户生成内容](https://zh.wikipedia.org/zh-hans/%E7%94%A8%E6%88%B7%E7%94%9F%E6%88%90%E5%86%85%E5%AE%B9)

请善用搜索引擎

**Comment by brlin-tw** [comment]
感谢
