### ISSUE TITLE
这里可能多了一个空格（There may be an extra space here）👇

### ISSUE THREAD

**Issue by HuberWong** [mzlogin/chinese-copywriting-guidelines#29]
<img width="524" alt="Snipaste_2021-06-29_14-43-18" src="https://user-images.githubusercontent.com/85234311/123749910-875d8f00-d8e8-11eb-9be2-ab34baa58f9c.png">

**Comment by mzlogin** [comment]
这里除了链接之外，还有「中英文」之间留白的规则，所以对比用法里左侧空格去掉了，右侧仍在。

**Comment by HuberWong** [comment]
非常感谢您的解答
