### ISSUE TITLE
申请添加纠正器到推荐工具中

### ISSUE THREAD

**Issue by ricoa** [mzlogin/chinese-copywriting-guidelines#6]
基于 [中文文案排版指北（简体中文版）](https://github.com/mzlogin/chinese-copywriting-guidelines) 为纠正规则，以 PHP 为开发语言开发了一个[中文文案排版纠正器](https://github.com/ricoa/copywriting-correct)，希望能添加项目到推荐工具中。

**Comment by mzlogin** [comment]
很赞的工具，我已经加进去了。你这个支持繁体中文不？我这个仓库是 fork 自一个繁体版，如果工具支持繁体，你可以到原仓库也提一个 PR，可以让更多的人看到和用到。

**Comment by ricoa** [comment]
好的 我晚点添加上繁体支持
